### PR TITLE
Bump version of php cs fixer to the latest

### PR DESCRIPTION
**Pull request by Kevin-koko**
The diff between versions: https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v3.1.0...v3.3.2 and release note page: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases

### CODE REVIEW

**Review by nikow13 — APPROVED** [review]

**Review by hmellouki — APPROVED** [review]

**Review by truffo — APPROVED** [review]

**Review by truffo — CHANGES_REQUESTED** [review]
No : Bump minimum PHP version to 7.2 since 3.3.0

Not all project are this version

**Comment by Samffy** [comment]
@truffo, our Github Action run on PHP 7.4/Alpine, I think there is no problem with @Kevin-koko pull request or I missed something ?  
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6067

**Comment by Kevin-koko** [comment]
I'm not scared

**Comment by truffo** [comment]
> @truffo, our Github Action run on PHP 7.4/Alpine, I think there is no problem with @Kevin-koko pull request or I missed something ? [FriendsOfPHP/PHP-CS-Fixer#6067](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6067)

@Samffy Yes, to have same comportement it's better to have same version. I don't think it's a good thing to mix PHP version when you works on a project.

**Review by truffo — APPROVED** [review]

**Pull request merged**
